package com.juzonce.customer.api

class ParamKey {

    companion object {

        const val TYPE = "type"
        const val LOGIN_NAME = "login_name"
        const val OTP = "otp"
        const val TITLE = "title"
        const val LAND_MARK = "landmark"
        const val CATEGORY_NAME = "category_name"
        const val BRAND_NAME = "brand_name"
        const val TRAVEL_STATUS = "travel_status"
        const val REASON = "reason"
        const val DATE = "date"
        const val TIME = "time"
        const val MODEL_NAME = "model_name"
        const val MODEL_ID = "model_id"
        const val PINCODE = "pincode"
        const val CATEGORY_ID = "category_id"
        const val BRAND_ID = "brand_id"
        const val ID = "id"
        const val DEVICE_ID = "device_id"
        const val DEVICE_TOKEN = "device_token"
        const val DEVICE_TYPE = "device_type"
        const val ACTION = "action"
        const val SEEN = "seen"
        const val TIME_STAMP = "timestamp"
        const val MESSAGE = "message"
        const val DESCRIPTION = "description"
        const val USER_ID = "user_id"
        const val AMOUNT = "amount"
        const val ADDRESS = "address"
        const val ADVOCATE_NAME = "advocate_name"
        const val MOBILE_NUMBER = "mobile_number"
        const val PASSWORD = "password"
        const val NAME = "name"
        const val EMAIL = "email"
        const val USER_NAME = "username"
        const val OLD_PASSWORD = "current_password"
        const val NEW_PASSWORD = "new_password"
        const val CONFIRM_PASSWORD = "confirm_password"
    }
}